const Elementos =[
    {
        atomicNumber: 1,
        symbol: "H",
        name: "Водород",
        atomicMass: "1.00794",
        electronicConfiguration: "1s1",
        electronegativity: 2.2,
        atomicRadius: 37,
        ionRadius: "Неизвестно",
        vanDerWaalsRadius: 120,
        ionizationEnergy: 1312,
        electronAffinity: -73,
        oxidationStates: "-1, 1",
        standardState: "Газообразный",
        bondingType: "diatomic",
        meltingPoint: 14,
        boilingPoint: 20,
        density: 0.0000899,
        groupBlock: "Неметалл",
        yearDiscovered: 1766,
        block: "s",
        cpkHexColor: "#76ED69",
        period: 1,
        group: 1
    },
    {
        atomicNumber: 2,
        symbol: "He",
        name: "Гелий",
        atomicMass: "4.002602",
        electronicConfiguration: "1s2",
        electronegativity: "Неизвестно",
        atomicRadius: 32,
        ionRadius: "Неизвестно",
        vanDerWaalsRadius: 140,
        ionizationEnergy: 2372,
        electronAffinity: 0,
        oxidationStates: "Неизвестно",
        standardState: "Газообразный",
        bondingType: "atomic",
        meltingPoint: "Неизвестно",
        boilingPoint: 4,
        density: 0.0001785,
        groupBlock: "Инертный газ",
        yearDiscovered: 1868,
        block: "p",
        cpkHexColor: "D9FFFF",
        period: 1,
        group: 18
    },
    {
        atomicNumber: 3,
        symbol: "Li",
        name: "Литий",
        atomicMass: "6.941",
        electronicConfiguration: "[He] 2s1",
        electronegativity: 0.98,
        atomicRadius: 134,
        ionRadius: "76 (+1)",
        vanDerWaalsRadius: 182,
        ionizationEnergy: 520,
        electronAffinity: -60,
        oxidationStates: 1,
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 454,
        boilingPoint: 1615,
        density: 0.535,
        groupBlock: "Щелочной металл",
        yearDiscovered: 1817,
        block: "s",
        cpkHexColor: "CC80FF",
        period: 2,
        group: 1
    },
    {
        atomicNumber: 4,
        symbol: "Be",
        name: "Бериллий",
        atomicMass: "9.012182",
        electronicConfiguration: "[He] 2s2",
        electronegativity: 1.57,
        atomicRadius: 90,
        ionRadius: "45 (+2)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 900,
        electronAffinity: 0,
        oxidationStates: 2,
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1560,
        boilingPoint: 2743,
        density: 1.848,
        groupBlock: "Щелочноземельный металл",
        yearDiscovered: 1798,
        block: "s",
        cpkHexColor: "C2FF00",
        period: 2,
        group: 2
    },
    {
        atomicNumber: 5,
        symbol: "B",
        name: "Бор",
        atomicMass: "10.811",
        electronicConfiguration: "[He] 2s2 2p1",
        electronegativity: 2.04,
        atomicRadius: 82,
        ionRadius: "27 (+3)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 801,
        electronAffinity: -27,
        oxidationStates: "1, 2, 3",
        standardState: "Твердый",
        bondingType: "covalent network",
        meltingPoint: 2348,
        boilingPoint: 4273,
        density: 2.46,
        groupBlock: "Полуметалл",
        yearDiscovered: 1807,
        block: "p",
        cpkHexColor: "FFB5B5",
        period: 1,
        group: 13
    },
    {
        atomicNumber: 6,
        symbol: "C",
        name: "Углерод",
        atomicMass: "12.0107",
        electronicConfiguration: "[He] 2s2 2p2",
        electronegativity: 2.55,
        atomicRadius: 77,
        ionRadius: "16 (+4)",
        vanDerWaalsRadius: 170,
        ionizationEnergy: 1087,
        electronAffinity: -154,
        oxidationStates: "-4, -3, -2, -1, 1, 2, 3, 4",
        standardState: "Твердый",
        bondingType: "covalent network",
        meltingPoint: 3823,
        boilingPoint: 4300,
        density: 2.26,
        groupBlock: "Неметалл",
        yearDiscovered: "Anciente",
        block: "p",
        cpkHexColor: "909090",
        period: 2,
        group: 14
    },
    {
        atomicNumber: 7,
        symbol: "N",
        name: "Азот",
        atomicMass: "14.0067",
        electronicConfiguration: "[He] 2s2 2p3",
        electronegativity: 3.04,
        atomicRadius: 75,
        ionRadius: "146 (-3)",
        vanDerWaalsRadius: 155,
        ionizationEnergy: 1402,
        electronAffinity: -7,
        oxidationStates: "-3, -2, -1, 1, 2, 3, 4, 5",
        standardState: "Газообразный",
        bondingType: "diatomic",
        meltingPoint: 63,
        boilingPoint: 77,
        density: 0.001251,
        groupBlock: "Неметалл",
        yearDiscovered: 1772,
        block: "p",
        cpkHexColor: "3050F8",
        period: 2,
        group: 15
    },
    {
        atomicNumber: 8,
        symbol: "O",
        name: "Кислород",
        atomicMass: "15.9994",
        electronicConfiguration: "[He] 2s2 2p4",
        electronegativity: 3.44,
        atomicRadius: 73,
        ionRadius: "140 (-2)",
        vanDerWaalsRadius: 152,
        ionizationEnergy: 1314,
        electronAffinity: -141,
        oxidationStates: "-2, -1, 1, 2",
        standardState: "Газообразный",
        bondingType: "diatomic",
        meltingPoint: 55,
        boilingPoint: 90,
        density: 0.001429,
        groupBlock: "Неметалл",
        yearDiscovered: 1774,
        block: "p",
        cpkHexColor: "FF0D0D",
        period: 2,
        group: 16
    },
    {
        atomicNumber: 9,
        symbol: "F",
        name: "Фтор",
        atomicMass: "18.9984",
        electronicConfiguration: "[He] 2s2 2p5",
        electronegativity: 3.98,
        atomicRadius: 71,
        ionRadius: "133 (-1)",
        vanDerWaalsRadius: 147,
        ionizationEnergy: 1681,
        electronAffinity: -328,
        oxidationStates: -1,
        standardState: "Газообразный",
        bondingType: "atomic",
        meltingPoint: 54,
        boilingPoint: 85,
        density: 0.001696,
        groupBlock: "Галлоген",
        yearDiscovered: 1670,
        block: "p",
        cpkHexColor: "9eaf51",
        period: 2,
        group: 17
    },
    {
        atomicNumber: 10,
        symbol: "Ne",
        name: "Неон",
        atomicMass: "20.1797",
        electronicConfiguration: "[He] 2s2 2p6",
        electronegativity: "Неизвестно",
        atomicRadius: 69,
        ionRadius: "Неизвестно",
        vanDerWaalsRadius: 154,
        ionizationEnergy: 2081,
        electronAffinity: 0,
        oxidationStates: "Неизвестно",
        standardState: "Газообразный",
        bondingType: "atomic",
        meltingPoint: 25,
        boilingPoint: 27,
        density: 0.0009,
        groupBlock: "Инертный газ",
        yearDiscovered: 1898,
        block: "p",
        cpkHexColor: "B3E3F5",
        period: 2,
        group: 18
    },
    {
        atomicNumber: 11,
        symbol: "Na",
        name: "Натрий",
        atomicMass: "22.99",
        electronicConfiguration: "[Ne] 3s1",
        electronegativity: 0.93,
        atomicRadius: 154,
        ionRadius: "102 (+1)",
        vanDerWaalsRadius: 227,
        ionizationEnergy: 496,
        electronAffinity: -53,
        oxidationStates: "-1, 1",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 371,
        boilingPoint: 1156,
        density: 0.968,
        groupBlock: "Щелочной металл",
        yearDiscovered: 1807,
        block: "s",
        cpkHexColor: "AB5CF2",
        period: 3,
        group: 1
    },
    {
        atomicNumber: 12,
        symbol: "Mg",
        name: "Магний",
        atomicMass: "24.31",
        electronicConfiguration: "[Ne] 3s2",
        electronegativity: 1.31,
        atomicRadius: 130,
        ionRadius: "72 (+2)",
        vanDerWaalsRadius: 173,
        ionizationEnergy: 738,
        electronAffinity: 0,
        oxidationStates: "1, 2",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 923,
        boilingPoint: 1363,
        density: 1.738,
        groupBlock: "Щелочноземельный металл",
        yearDiscovered: 1808,
        block: "s",
        cpkHexColor: "8AFF00",
        period: 3,
        group: 2
    },
    {
        atomicNumber: 13,
        symbol: "Al",
        name: "Аллюминий",
        atomicMass: "26.98",
        electronicConfiguration: "[Ne] 3s2 3p1",
        electronegativity: 1.61,
        atomicRadius: 118,
        ionRadius: "53.5 (+3)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 578,
        electronAffinity: -43,
        oxidationStates: "1, 3",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 933,
        boilingPoint: 2792,
        density: 2.7,
        groupBlock: "Металл",
        yearDiscovered: "Anciente",
        block: "p",
        cpkHexColor: "BFA6A6",
        period: 3,
        group: 13
    },
    {
        atomicNumber: 14,
        symbol: "Si",
        name: "Кремний",
        atomicMass: "28.09",
        electronicConfiguration: "[Ne] 3s2 3p2",
        electronegativity: 1.9,
        atomicRadius: 111,
        ionRadius: "40 (+4)",
        vanDerWaalsRadius: 210,
        ionizationEnergy: 787,
        electronAffinity: -134,
        oxidationStates: "-4, -3, -2, -1, 1, 2, 3, 4",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1687,
        boilingPoint: 3173,
        density: 2.33,
        groupBlock: "Полуметалл",
        yearDiscovered: 1854,
        block: "p",
        cpkHexColor: "F0C8A0",
        period: 3,
        group: 14
    },
    {
        atomicNumber: 15,
        symbol: "P",
        name: "Фосфор",
        atomicMass: "30.97",
        electronicConfiguration: "[Ne] 3s2 3p3",
        electronegativity: 2.19,
        atomicRadius: 106,
        ionRadius: "44 (+3)",
        vanDerWaalsRadius: 180,
        ionizationEnergy: 1012,
        electronAffinity: -72,
        oxidationStates: "-3, -2, -1, 1, 2, 3, 4, 5",
        standardState: "Твердый",
        bondingType: "covalent network",
        meltingPoint: 317,
        boilingPoint: 554,
        density: 1.823,
        groupBlock: "Неметалл",
        yearDiscovered: 1669,
        block: "p",
        cpkHexColor: "FF8000",
        period: 3,
        group: 15
    },
    {
        atomicNumber: 16,
        symbol: "S",
        name: "Сера",
        atomicMass: "32.07",
        electronicConfiguration: "[Ne] 3s2 3p4",
        electronegativity: 2.58,
        atomicRadius: 102,
        ionRadius: "184 (-2)",
        vanDerWaalsRadius: 180,
        ionizationEnergy: 1000,
        electronAffinity: -200,
        oxidationStates: "-2, -1, 1, 2, 3, 4, 5, 6",
        standardState: "Твердый",
        bondingType: "covalent network",
        meltingPoint: 388,
        boilingPoint: 718,
        density: 1.96,
        groupBlock: "Неметалл",
        yearDiscovered: "Anciente",
        block: "p",
        cpkHexColor: "FFFF30",
        period: 3,
        group: 16
    },
    {
        atomicNumber: 17,
        symbol: "Cl",
        name: "Хлор",
        atomicMass: "35.45",
        electronicConfiguration: "[Ne] 3s2 3p5",
        electronegativity: 3.16,
        atomicRadius: 99,
        ionRadius: "181 (-1)",
        vanDerWaalsRadius: 175,
        ionizationEnergy: 1251,
        electronAffinity: -349,
        oxidationStates: "-1, 1, 2, 3, 4, 5, 6, 7",
        standardState: "Газообразный",
        bondingType: "covalent network",
        meltingPoint: 172,
        boilingPoint: 239,
        density: 0.003214,
        groupBlock: "Галлоген",
        yearDiscovered: 1774,
        block: "p",
        cpkHexColor: "1FF01F",
        period: 3,
        group: 17
    },
    {
        atomicNumber: 18,
        symbol: "Ar",
        name: "Аргон",
        atomicMass: "39.95",
        electronicConfiguration: "[Ne] 3s2 3p6",
        electronegativity: "Неизвестно",
        atomicRadius: 97,
        ionRadius: "Неизвестно",
        vanDerWaalsRadius: 188,
        ionizationEnergy: 1521,
        electronAffinity: 0,
        oxidationStates: "Неизвестно",
        standardState: "Газообразный",
        bondingType: "atomic",
        meltingPoint: 84,
        boilingPoint: 87,
        density: 0.001784,
        groupBlock: "Инертный газ",
        yearDiscovered: 1894,
        block: "p",
        cpkHexColor: "80D1E3",
        period: 3,
        group: 18
    },
    {
        atomicNumber: 19,
        symbol: "K",
        name: "Калий",
        atomicMass: "39.098",
        electronicConfiguration: "[Ar] 4s1",
        electronegativity: 0.82,
        atomicRadius: 196,
        ionRadius: "138 (+1)",
        vanDerWaalsRadius: 275,
        ionizationEnergy: 419,
        electronAffinity: -48,
        oxidationStates: 1,
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 337,
        boilingPoint: 1032,
        density: 0.856,
        groupBlock: "Щелочной металл",
        yearDiscovered: 1807,
        block: "s",
        cpkHexColor: "8F40D4",
        period: 4,
        group: 1
    },
    {
        atomicNumber: 20,
        symbol: "Ca",
        name: "Кальций",
        atomicMass: "40.08",
        electronicConfiguration: "[Ar] 4s2",
        electronegativity: 1,
        atomicRadius: 174,
        ionRadius: "100 (+2)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 590,
        electronAffinity: -2,
        oxidationStates: 2,
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1115,
        boilingPoint: 1757,
        density: 1.55,
        groupBlock: "Щелочноземельный металл",
        yearDiscovered: "Anciente",
        block: "s",
        cpkHexColor: "3DFF00",
        period: 4,
        group: 2
    },
    {
        atomicNumber: 21,
        symbol: "Sc",
        name: "Скандий",
        atomicMass: "44.96",
        electronicConfiguration: "[Ar] 3d1 4s2",
        electronegativity: 1.36,
        atomicRadius: 144,
        ionRadius: "74.5 (+3)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 633,
        electronAffinity: -18,
        oxidationStates: "1, 2, 3",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1814,
        boilingPoint: 3103,
        density: 2.985,
        groupBlock: "Полупроводник",
        yearDiscovered: 1876,
        block: "d",
        cpkHexColor: "E6E6E6",
        period: 4,
        group: 3
    },
    {
        atomicNumber: 22,
        symbol: "Ti",
        name: "Титан",
        atomicMass: "47.87",
        electronicConfiguration: "[Ar] 3d2 4s2",
        electronegativity: 1.54,
        atomicRadius: 136,
        ionRadius: "86 (+2)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 659,
        electronAffinity: -8,
        oxidationStates: "-1, 2, 3, 4",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1941,
        boilingPoint: 3560,
        density: 4.507,
        groupBlock: "Полупроводник",
        yearDiscovered: 1791,
        block: "d",
        cpkHexColor: "BFC2C7",
        period: 4,
        group: 4
    },
    {
        atomicNumber: 23,
        symbol: "V",
        name: "Ванадий",
        atomicMass: "50.94",
        electronicConfiguration: "[Ar] 3d3 4s2",
        electronegativity: 1.63,
        atomicRadius: 125,
        ionRadius: "79 (+2)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 651,
        electronAffinity: -51,
        oxidationStates: "-1, 2, 3, 4",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 2183,
        boilingPoint: 3680,
        density: 6.11,
        groupBlock: "Полупроводник",
        yearDiscovered: 1803,
        block: "d",
        cpkHexColor: "A6A6AB",
        period: 4,
        group: 5
    },
    {
        atomicNumber: 24,
        symbol: "Cr",
        name: "Хром",
        atomicMass: "51.996",
        electronicConfiguration: "[Ar] 3d5 4s1",
        electronegativity: 1.66,
        atomicRadius: 127,
        ionRadius: "80 (+2*)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 653,
        electronAffinity: -64,
        oxidationStates: "-2, -1, 1, 2, 3, 4, 5, 6",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 2180,
        boilingPoint: 2944,
        density: 7.14,
        groupBlock: "Полупроводник",
        yearDiscovered: "Anciente",
        block: "d",
        cpkHexColor: "8A99C7",
        period: 4,
        group: 6
    },
    {
        atomicNumber: 25,
        symbol: "Mn",
        name: "Марганец",
        atomicMass: "54.938",
        electronicConfiguration: "[Ar] 3d5 4s2",
        electronegativity: 1.55,
        atomicRadius: 139,
        ionRadius: "67 (+2)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 717,
        electronAffinity: 0,
        oxidationStates: "-3, -2, -1, 1, 2, 3, 4, 5, 6, 7",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1519,
        boilingPoint: 2334,
        density: 7.47,
        groupBlock: "Полупроводник",
        yearDiscovered: 1774,
        block: "d",
        cpkHexColor: "9C7AC7",
        period: 4,
        group: 7
    },
    {
        atomicNumber: 26,
        symbol: "Fe",
        name: "Железо",
        atomicMass: "55.845",
        electronicConfiguration: "[Ar] 3d6 4s2",
        electronegativity: 1.83,
        atomicRadius: 125,
        ionRadius: "78 (+2*)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 763,
        electronAffinity: -16,
        oxidationStates: "-2, -1, 1, 2, 3, 4, 5, 6",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1811,
        boilingPoint: 3134,
        density: 7.874,
        groupBlock: "Полупроводник",
        yearDiscovered: "Anciente",
        block: "d",
        cpkHexColor: "E06633",
        period: 4,
        group: 8
    },
    {
        atomicNumber: 27,
        symbol: "Co",
        name: "Кобальт",
        atomicMass: "58.933",
        electronicConfiguration: "[Ar] 3d7 4s2",
        electronegativity: 1.88,
        atomicRadius: 126,
        ionRadius: "74.5 (+2*)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 760,
        electronAffinity: -64,
        oxidationStates: "-1, 1, 2, 3, 4, 5",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1768,
        boilingPoint: 3200,
        density: 8.9,
        groupBlock: "Полупроводник",
        yearDiscovered: "Anciente",
        block: "d",
        cpkHexColor: "F090A0",
        period: 4,
        group: 9
    },
    {
        atomicNumber: 28,
        symbol: "Ni",
        name: "Никель",
        atomicMass: "58.693",
        electronicConfiguration: "[Ar] 3d8 4s2",
        electronegativity: 1.91,
        atomicRadius: 121,
        ionRadius: "69 (+2)",
        vanDerWaalsRadius: 163,
        ionizationEnergy: 737,
        electronAffinity: -112,
        oxidationStates: "-1, 1, 2, 3, 4",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1728,
        boilingPoint: 3186,
        density: 8.908,
        groupBlock: "Полупроводник",
        yearDiscovered: 1751,
        block: "d",
        cpkHexColor: "50D050",
        period: 4,
        group: 10
    },
    {
        atomicNumber: 29,
        symbol: "Cu",
        name: "Медь",
        atomicMass: "63.546",
        electronicConfiguration: "[Ar] 3d10 4s1",
        electronegativity: 1.9,
        atomicRadius: 138,
        ionRadius: "77 (+1)",
        vanDerWaalsRadius: 140,
        ionizationEnergy: 746,
        electronAffinity: -118,
        oxidationStates: "1, 2, 3, 4",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1358,
        boilingPoint: 3200,
        density: 8.92,
        groupBlock: "Полупроводник",
        yearDiscovered: "Anciente",
        block: "d",
        cpkHexColor: "C88033",
        period: 4,
        group: 11
    },
    {
        atomicNumber: 30,
        symbol: "Zn",
        name: "Цинк",
        atomicMass: "65.38",
        electronicConfiguration: "[Ar] 3d10 4s2",
        electronegativity: 1.65,
        atomicRadius: 131,
        ionRadius: "74 (+2)",
        vanDerWaalsRadius: 139,
        ionizationEnergy: 906,
        electronAffinity: 0,
        oxidationStates: 2,
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 693,
        boilingPoint: 1180,
        density: 7.14,
        groupBlock: "Полупроводник",
        yearDiscovered: 1746,
        block: "d",
        cpkHexColor: "7D80B0",
        period: 4,
        group: 12
    },
    {
        atomicNumber: 31,
        symbol: "Ga",
        name: "Галий",
        atomicMass: "69.723",
        electronicConfiguration: "[Ar] 3d10 4s2 4p1",
        electronegativity: 1.81,
        atomicRadius: 126,
        ionRadius: "62 (+3)",
        vanDerWaalsRadius: 187,
        ionizationEnergy: 579,
        electronAffinity: -29,
        oxidationStates: "1, 2, 3",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 303,
        boilingPoint: 2477,
        density: 5.904,
        groupBlock: "Металл",
        yearDiscovered: 1875,
        block: "p",
        cpkHexColor: "C28F8F",
        period: 4,
        group: 13
    },
    {
        atomicNumber: 32,
        symbol: "Ge",
        name: "Германий",
        atomicMass: "72.64",
        electronicConfiguration: "[Ar] 3d10 4s2 4p2",
        electronegativity: 2.01,
        atomicRadius: 122,
        ionRadius: "73 (+2)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 762,
        electronAffinity: -119,
        oxidationStates: "-4, 1, 2, 3, 4",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1211,
        boilingPoint: 3093,
        density: 5.323,
        groupBlock: "Полуметалл",
        yearDiscovered: 1886,
        block: "p",
        cpkHexColor: "668F8F",
        period: 4,
        group: 14
    },
    {
        atomicNumber: 33,
        symbol: "As",
        name: "Мышьяк",
        atomicMass: "74.921",
        electronicConfiguration: "[Ar] 3d10 4s2 4p3",
        electronegativity: 2.18,
        atomicRadius: 119,
        ionRadius: "58 (+3)",
        vanDerWaalsRadius: 185,
        ionizationEnergy: 947,
        electronAffinity: -78,
        oxidationStates: "-3, 2, 3, 5",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1090,
        boilingPoint: 887,
        density: 5.727,
        groupBlock: "Полуметалл",
        yearDiscovered: "Anciente",
        block: "p",
        cpkHexColor: "BD80E3",
        period: 4,
        group: 15
    },
    {
        atomicNumber: 34,
        symbol: "Se",
        name: "Селен",
        atomicMass: "78.96",
        electronicConfiguration: "[Ar] 3d10 4s2 4p4",
        electronegativity: 2.55,
        atomicRadius: 116,
        ionRadius: "198 (-2)",
        vanDerWaalsRadius: 190,
        ionizationEnergy: 941,
        electronAffinity: -195,
        oxidationStates: "-2, 2, 4, 6",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 494,
        boilingPoint: 958,
        density: 4.819,
        groupBlock: "Неметалл",
        yearDiscovered: 1817,
        block: "p",
        cpkHexColor: "FFA100",
        period: 4,
        group: 16
    },
    {
        atomicNumber: 35,
        symbol: "Br",
        name: "Бром",
        atomicMass: "79.904",
        electronicConfiguration: "[Ar] 3d10 4s2 4p5",
        electronegativity: 2.96,
        atomicRadius: 114,
        ionRadius: "196 (-1)",
        vanDerWaalsRadius: 185,
        ionizationEnergy: 1140,
        electronAffinity: -325,
        oxidationStates: "-1, 1, 3, 4, 5, 7",
        standardState: "Жидкий",
        bondingType: "covalent network",
        meltingPoint: 266,
        boilingPoint: 332,
        density: 3.12,
        groupBlock: "Галлоген",
        yearDiscovered: 1826,
        block: "p",
        cpkHexColor: "A62929",
        period: 4,
        group: 17
    },
    {
        atomicNumber: 36,
        symbol: "Kr",
        name: "Криптон",
        atomicMass: "83.798",
        electronicConfiguration: "[Ar] 3d10 4s2 4p6",
        electronegativity: "Неизвестно",
        atomicRadius: 110,
        ionRadius: "Неизвестно",
        vanDerWaalsRadius: 202,
        ionizationEnergy: 1351,
        electronAffinity: 0,
        oxidationStates: 2,
        standardState: "Газообразный",
        bondingType: "atomic",
        meltingPoint: 116,
        boilingPoint: 120,
        density: 0.00375,
        groupBlock: "Инертный газ",
        yearDiscovered: 1898,
        block: "p",
        cpkHexColor: "5CB8D1",
        period: 4,
        group: 18
    },
    {
        atomicNumber: 37,
        symbol: "Rb",
        name: "Рубидий",
        atomicMass: "85.468",
        electronicConfiguration: "[Kr] 5s1",
        electronegativity: 0.82,
        atomicRadius: 211,
        ionRadius: "152 (+1)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 403,
        electronAffinity: -47,
        oxidationStates: 1,
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 312,
        boilingPoint: 961,
        density: 1.532,
        groupBlock: "Щелочной металл",
        yearDiscovered: 1861,
        block: "s",
        cpkHexColor: "702EB0",
        period: 5,
        group: 1
    },
    {
        atomicNumber: 38,
        symbol: "Sr",
        name: "Стронций",
        atomicMass: "87.62",
        electronicConfiguration: "[Kr] 5s2",
        electronegativity: 0.95,
        atomicRadius: 192,
        ionRadius: "118 (+2)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 550,
        electronAffinity: -5,
        oxidationStates: 2,
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1050,
        boilingPoint: 1655,
        density: 2.63,
        groupBlock: "Щелочноземельный металл",
        yearDiscovered: 1790,
        block: "s",
        cpkHexColor: "00FF00",
        period: 5,
        group: 2
    },
    {
        atomicNumber: 39,
        symbol: "Y",
        name: "Итрий",
        atomicMass: "88.906",
        electronicConfiguration: "[Kr] 4d1 5s2",
        electronegativity: 1.22,
        atomicRadius: 162,
        ionRadius: "90 (+3)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 600,
        electronAffinity: -30,
        oxidationStates: "1, 2, 3",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1799,
        boilingPoint: 3618,
        density: 4.472,
        groupBlock: "Полупроводник",
        yearDiscovered: 1794,
        block: "d",
        cpkHexColor: "94FFFF",
        period: 5,
        group: 3
    },
    {
        atomicNumber: 40,
        symbol: "Zr",
        name: "Цирконий",
        atomicMass: "91.224",
        electronicConfiguration: "[Kr] 4d2 5s2",
        electronegativity: 1.33,
        atomicRadius: 148,
        ionRadius: "72 (+4)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 640,
        electronAffinity: -41,
        oxidationStates: "1, 2, 3, 4",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 2128,
        boilingPoint: 4682,
        density: 6.511,
        groupBlock: "Полупроводник",
        yearDiscovered: 1789,
        block: "d",
        cpkHexColor: "94E0E0",
        period: 5,
        group: 4
    },
    {
        atomicNumber: 41,
        symbol: "Nb",
        name: "Ниобий",
        atomicMass: "92.906",
        electronicConfiguration: "[Kr] 4d4 5s1",
        electronegativity: 1.6,
        atomicRadius: 137,
        ionRadius: "72 (+3)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 652,
        electronAffinity: -86,
        oxidationStates: "-1, 2, 3, 4, 5",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 2750,
        boilingPoint: 5017,
        density: 8.57,
        groupBlock: "Полупроводник",
        yearDiscovered: 1801,
        block: "d",
        cpkHexColor: "73C2C9",
        period: 5,
        group: 5
    },
    {
        atomicNumber: 42,
        symbol: "Mo",
        name: "Молибден",
        atomicMass: "95.96",
        electronicConfiguration: "[Kr] 4d5 5s1",
        electronegativity: 2.16,
        atomicRadius: 145,
        ionRadius: "69 (+3)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 684,
        electronAffinity: -72,
        oxidationStates: "-2, -1, 1, 2, 3, 4, 5, 6",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 2896,
        boilingPoint: 4912,
        density: 10.28,
        groupBlock: "Полупроводник",
        yearDiscovered: 1778,
        block: "d",
        cpkHexColor: "54B5B5",
        period: 5,
        group: 6
    },
    {
        atomicNumber: 43,
        symbol: "Tc",
        name: "Технеций",
        atomicMass: "98",
        electronicConfiguration: "[Kr] 4d5 5s2",
        electronegativity: 1.9,
        atomicRadius: 156,
        ionRadius: "64.5 (+4)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 702,
        electronAffinity: -53,
        oxidationStates: "-3, -1, 1, 2, 3, 4, 5, 6, 7",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 2430,
        boilingPoint: 4538,
        density: 11.5,
        groupBlock: "Полупроводник",
        yearDiscovered: 1937,
        block: "d",
        cpkHexColor: "3B9E9E",
        period: 5,
        group: 7
    },
    {
        atomicNumber: 44,
        symbol: "Ru",
        name: "Рутений",
        atomicMass: "101.07",
        electronicConfiguration: "[Kr] 4d7 5s1",
        electronegativity: 2.2,
        atomicRadius: 126,
        ionRadius: "68 (+3)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 710,
        electronAffinity: -101,
        oxidationStates: "-2, 1, 2, 3, 4, 5, 6, 7, 8",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 2607,
        boilingPoint: 4423,
        density: 12.37,
        groupBlock: "Полупроводник",
        yearDiscovered: 1827,
        block: "d",
        cpkHexColor: "248F8F",
        period: 5,
        group: 8
    },
    {
        atomicNumber: 45,
        symbol: "Rh",
        name: "Родий",
        atomicMass: "102.906",
        electronicConfiguration: "[Kr] 4d8 5s1",
        electronegativity: 2.28,
        atomicRadius: 135,
        ionRadius: "66.5 (+3)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 720,
        electronAffinity: -110,
        oxidationStates: "-1, 1, 2, 3, 4, 5, 6",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 2237,
        boilingPoint: 3968,
        density: 12.45,
        groupBlock: "Полупроводник",
        yearDiscovered: 1803,
        block: "d",
        cpkHexColor: "0A7D8C",
        period: 5,
        group: 9
    },
    {
        atomicNumber: 46,
        symbol: "Pd",
        name: "Палладий",
        atomicMass: "106.42",
        electronicConfiguration: "[Kr] 4d10",
        electronegativity: 2.2,
        atomicRadius: 131,
        ionRadius: "59 (+1)",
        vanDerWaalsRadius: 163,
        ionizationEnergy: 804,
        electronAffinity: -54,
        oxidationStates: "2, 4",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1828,
        boilingPoint: 3236,
        density: 12.023,
        groupBlock: "Полупроводник",
        yearDiscovered: 1803,
        block: "d",
        cpkHexColor: "6985",
        period: 5,
        group: 10
    },
    {
        atomicNumber: 47,
        symbol: "Ag",
        name: "Золото",
        atomicMass: "107.868",
        electronicConfiguration: "[Kr] 4d10 5s1",
        electronegativity: 1.93,
        atomicRadius: 153,
        ionRadius: "115 (+1)",
        vanDerWaalsRadius: 172,
        ionizationEnergy: 731,
        electronAffinity: -126,
        oxidationStates: "1, 2, 3",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1235,
        boilingPoint: 2435,
        density: 10.49,
        groupBlock: "Полупроводник",
        yearDiscovered: "Anciente",
        block: "d",
        cpkHexColor: "C0C0C0",
        period: 5,
        group: 11
    },
    {
        atomicNumber: 48,
        symbol: "Cd",
        name: "Кадмий",
        atomicMass: "112.411",
        electronicConfiguration: "[Kr] 4d10 5s2",
        electronegativity: 1.69,
        atomicRadius: 148,
        ionRadius: "95 (+2)",
        vanDerWaalsRadius: 158,
        ionizationEnergy: 868,
        electronAffinity: 0,
        oxidationStates: 2,
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 594,
        boilingPoint: 1040,
        density: 8.65,
        groupBlock: "Полупроводник",
        yearDiscovered: 1817,
        block: "d",
        cpkHexColor: "FFD98F",
        period: 5,
        group: 12
    },
    {
        atomicNumber: 49,
        symbol: "In",
        name: "Индий",
        atomicMass: "114.818",
        electronicConfiguration: "[Kr] 4d10 5s2 5p1",
        electronegativity: 1.78,
        atomicRadius: 144,
        ionRadius: "80 (+3)",
        vanDerWaalsRadius: 193,
        ionizationEnergy: 558,
        electronAffinity: -29,
        oxidationStates: "1, 2, 3",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 430,
        boilingPoint: 2345,
        density: 7.31,
        groupBlock: "Металл",
        yearDiscovered: 1863,
        block: "p",
        cpkHexColor: "A67573",
        period: 5,
        group: 13
    },
    {
        atomicNumber: 50,
        symbol: "Sn",
        name: "Олово",
        atomicMass: "118.710",
        electronicConfiguration: "[Kr] 4d10 5s2 5p2",
        electronegativity: 1.96,
        atomicRadius: 141,
        ionRadius: "112 (+2)",
        vanDerWaalsRadius: 217,
        ionizationEnergy: 709,
        electronAffinity: -107,
        oxidationStates: "-4, 2, 4",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 505,
        boilingPoint: 2875,
        density: 7.31,
        groupBlock: "Металл",
        yearDiscovered: "Anciente",
        block: "p",
        cpkHexColor: "668080",
        period: 5,
        group: 14
    },
    {
        atomicNumber: 51,
        symbol: "Sb",
        name: "Сурьма",
        atomicMass: "121.760",
        electronicConfiguration: "[Kr] 4d10 5s2 5p3",
        electronegativity: 2.05,
        atomicRadius: 138,
        ionRadius: "76 (+3)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 834,
        electronAffinity: -103,
        oxidationStates: "-3, 3, 5",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 904,
        boilingPoint: 1860,
        density: 6.697,
        groupBlock: "Полуметалл",
        yearDiscovered: "Anciente",
        block: "p",
        cpkHexColor: "9E63B5",
        period: 5,
        group: 15
    },
    {
        atomicNumber: 52,
        symbol: "Te",
        name: "Теллур",
        atomicMass: "127.60",
        electronicConfiguration: "[Kr] 4d10 5s2 5p4",
        electronegativity: 2.1,
        atomicRadius: 135,
        ionRadius: "221 (-2)",
        vanDerWaalsRadius: 206,
        ionizationEnergy: 869,
        electronAffinity: -190,
        oxidationStates: "-2, 2, 4, 5, 6",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 723,
        boilingPoint: 1261,
        density: 6.24,
        groupBlock: "Полуметалл",
        yearDiscovered: 1782,
        block: "p",
        cpkHexColor: "D47A00",
        period: 5,
        group: 16
    },
    {
        atomicNumber: 53,
        symbol: "I",
        name: "Иод",
        atomicMass: "126.904",
        electronicConfiguration: "[Kr] 4d10 5s2 5p5",
        electronegativity: 2.66,
        atomicRadius: 133,
        ionRadius: "220 (-1)",
        vanDerWaalsRadius: 198,
        ionizationEnergy: 1008,
        electronAffinity: -295,
        oxidationStates: "-1, 1, 3, 5, 7",
        standardState: "Твердый",
        bondingType: "covalent network",
        meltingPoint: 387,
        boilingPoint: 457,
        density: 4.94,
        groupBlock: "Галлоген",
        yearDiscovered: 1811,
        block: "p",
        cpkHexColor: "940094",
        period: 5,
        group: 17
    },
    {
        atomicNumber: 54,
        symbol: "Xe",
        name: "Ксенон",
        atomicMass: "131.293",
        electronicConfiguration: "[Kr] 4d10 5s2 5p6",
        electronegativity: "Неизвестно",
        atomicRadius: 130,
        ionRadius: "48 (+8)",
        vanDerWaalsRadius: 216,
        ionizationEnergy: 1170,
        electronAffinity: 0,
        oxidationStates: "2, 4, 6, 8",
        standardState: "Газообразный",
        bondingType: "atomic",
        meltingPoint: 161,
        boilingPoint: 165,
        density: 0.0059,
        groupBlock: "Инертный газ",
        yearDiscovered: 1898,
        block: "p",
        cpkHexColor: "429EB0",
        period: 5,
        group: 18
    },
    {
        atomicNumber: 55,
        symbol: "Cs",
        name: "Цезий",
        atomicMass: "132.905",
        electronicConfiguration: "[Xe] 6s1",
        electronegativity: 0.79,
        atomicRadius: 225,
        ionRadius: "167 (+1)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 376,
        electronAffinity: -46,
        oxidationStates: 1,
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 302,
        boilingPoint: 944,
        density: 1.879,
        groupBlock: "Щелочной металл",
        yearDiscovered: 1860,
        block: "s",
        cpkHexColor: "57178F",
        period: 6,
        group: 1
    },
    {
        atomicNumber: 56,
        symbol: "Ba",
        name: "Барий",
        atomicMass: "137.327",
        electronicConfiguration: "[Xe] 6s2",
        electronegativity: 0.89,
        atomicRadius: 198,
        ionRadius: "135 (+2)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 503,
        electronAffinity: -14,
        oxidationStates: 2,
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1000,
        boilingPoint: 2143,
        density: 3.51,
        groupBlock: "Щелочноземельный металл",
        yearDiscovered: 1808,
        block: "s",
        cpkHexColor: "00C900",
        period: 6,
        group: 2
    },
    {
        atomicNumber: 57,
        symbol: "La",
        name: "Лантан",
        atomicMass: "138.905",
        electronicConfiguration: "[Xe] 5d1 6s2",
        electronegativity: 1.1,
        atomicRadius: 169,
        ionRadius: "103.2 (+3)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 538,
        electronAffinity: -48,
        oxidationStates: "2, 3",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1193,
        boilingPoint: 3737,
        density: 6.146,
        groupBlock: "Лантанид",
        yearDiscovered: 1839,
        block: "f",
        cpkHexColor: "70D4FF",
        period: 6,
        group: 3
    },
    {
        atomicNumber: 58,
        symbol: "Ce",
        name: "Церий",
        atomicMass: "140.116",
        electronicConfiguration: "[Xe] 4f1 5d1 6s2",
        electronegativity: 1.12,
        atomicRadius: "Неизвестно",
        ionRadius: "102 (+3)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 534,
        electronAffinity: -50,
        oxidationStates: "2, 3, 4",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1071,
        boilingPoint: 3633,
        density: 6.689,
        groupBlock: "Лантанид",
        yearDiscovered: 1803,
        block: "f",
        cpkHexColor: "FFFFC7",
        period: 6,
        group: 3
    },
    {
        atomicNumber: 59,
        symbol: "Pr",
        name: "Празеодим",
        atomicMass: "140.908",
        electronicConfiguration: "[Xe] 4f3 6s2",
        electronegativity: 1.13,
        atomicRadius: "Неизвестно",
        ionRadius: "99 (+3)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 527,
        electronAffinity: -50,
        oxidationStates: "2, 3, 4",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1204,
        boilingPoint: 3563,
        density: 6.64,
        groupBlock: "Лантанид",
        yearDiscovered: 1885,
        block: "f",
        cpkHexColor: "D9FFC7",
        period: 6,
        group: 3
    },
    {
        atomicNumber: 60,
        symbol: "Nd",
        name: "Неодим",
        atomicMass: "144.242",
        electronicConfiguration: "[Xe] 4f4 6s2",
        electronegativity: 1.14,
        atomicRadius: "Неизвестно",
        ionRadius: "129 (+2)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 533,
        electronAffinity: -50,
        oxidationStates: "2, 3",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1294,
        boilingPoint: 3373,
        density: 7.01,
        groupBlock: "Лантанид",
        yearDiscovered: 1885,
        block: "f",
        cpkHexColor: "C7FFC7",
        period: 6,
        group: 3
    },
    {
        atomicNumber: 61,
        symbol: "Pm",
        name: "Прометий",
        atomicMass: "145",
        electronicConfiguration: "[Xe] 4f5 6s2",
        electronegativity: 1.13,
        atomicRadius: "Неизвестно",
        ionRadius: "97 (+3)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 540,
        electronAffinity: -50,
        oxidationStates: 3,
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1373,
        boilingPoint: 3273,
        density: 7.264,
        groupBlock: "Лантанид",
        yearDiscovered: 1947,
        block: "f",
        cpkHexColor: "A3FFC7",
        period: 6,
        group: 3
    },
    {
        atomicNumber: 62,
        symbol: "Sm",
        name: "Самарий",
        atomicMass: "150.36",
        electronicConfiguration: "[Xe] 4f6 6s2",
        electronegativity: 1.17,
        atomicRadius: "Неизвестно",
        ionRadius: "122 (+2)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 545,
        electronAffinity: -50,
        oxidationStates: "2, 3",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1345,
        boilingPoint: 2076,
        density: 7.353,
        groupBlock: "Лантанид",
        yearDiscovered: 1853,
        block: "f",
        cpkHexColor: "8FFFC7",
        period: 6,
        group: 3
    },
    {
        atomicNumber: 63,
        symbol: "Eu",
        name: "Eвропий",
        atomicMass: "151.964",
        electronicConfiguration: "[Xe] 4f7 6s2",
        electronegativity: 1.2,
        atomicRadius: "Неизвестно",
        ionRadius: "117 (+2)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 547,
        electronAffinity: -50,
        oxidationStates: "2, 3",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1095,
        boilingPoint: 1800,
        density: 5.244,
        groupBlock: "Лантанид",
        yearDiscovered: 1901,
        block: "f",
        cpkHexColor: "61FFC7",
        period: 6,
        group: 3
    },
    {
        atomicNumber: 64,
        symbol: "Gd",
        name: "Гадолиний",
        atomicMass: "157.25",
        electronicConfiguration: "[Xe] 4f7 5d1 6s2",
        electronegativity: 1.2,
        atomicRadius: "Неизвестно",
        ionRadius: "93.8 (+3)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 593,
        electronAffinity: -50,
        oxidationStates: "1, 2, 3",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1586,
        boilingPoint: 3523,
        density: 7.901,
        groupBlock: "Лантанид",
        yearDiscovered: 1880,
        block: "f",
        cpkHexColor: "45FFC7",
        period: 6,
        group: 3
    },
    {
        atomicNumber: 65,
        symbol: "Tb",
        name: "Тербий",
        atomicMass: "158.925",
        electronicConfiguration: "[Xe] 4f9 6s2",
        electronegativity: 1.2,
        atomicRadius: "Неизвестно",
        ionRadius: "92.3 (+3)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 566,
        electronAffinity: -50,
        oxidationStates: "1, 3, 4",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1629,
        boilingPoint: 3503,
        density: 8.219,
        groupBlock: "Лантанид",
        yearDiscovered: 1843,
        block: "f",
        cpkHexColor: "30FFC7",
        period: 6,
        group: 3
    },
    {
        atomicNumber: 66,
        symbol: "Dy",
        name: "Disprósio",
        atomicMass: "162.500",
        electronicConfiguration: "[Xe] 4f10 6s2",
        electronegativity: 1.22,
        atomicRadius: "Неизвестно",
        ionRadius: "107 (+2)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 573,
        electronAffinity: -50,
        oxidationStates: "2, 3",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1685,
        boilingPoint: 2840,
        density: 8.551,
        groupBlock: "Лантанид",
        yearDiscovered: 1886,
        block: "f",
        cpkHexColor: "1FFFC7",
        period: 6,
        group: 3
    },
    {
        atomicNumber: 67,
        symbol: "Ho",
        name: "Hólmio",
        atomicMass: "164.930",
        electronicConfiguration: "[Xe] 4f11 6s2",
        electronegativity: 1.23,
        atomicRadius: "Неизвестно",
        ionRadius: "90.1 (+3)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 581,
        electronAffinity: -50,
        oxidationStates: 3,
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1747,
        boilingPoint: 2973,
        density: 8.795,
        groupBlock: "Лантанид",
        yearDiscovered: 1878,
        block: "f",
        cpkHexColor: "00FF9C",
        period: 6,
        group: 3
    },
    {
        atomicNumber: 68,
        symbol: "Er",
        name: "Érbio",
        atomicMass: "167.259",
        electronicConfiguration: "[Xe] 4f12 6s2",
        electronegativity: 1.24,
        atomicRadius: "Неизвестно",
        ionRadius: "89 (+3)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 589,
        electronAffinity: -50,
        oxidationStates: 3,
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1770,
        boilingPoint: 3141,
        density: 9.066,
        groupBlock: "Лантанид",
        yearDiscovered: 1842,
        block: "f",
        cpkHexColor: "0",
        period: 6,
        group: 3
    },
    {
        atomicNumber: 69,
        symbol: "Tm",
        name: "Túlio",
        atomicMass: "168.934",
        electronicConfiguration: "[Xe] 4f13 6s2",
        electronegativity: 1.25,
        atomicRadius: "Неизвестно",
        ionRadius: "103 (+2)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 597,
        electronAffinity: -50,
        oxidationStates: "2, 3",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1818,
        boilingPoint: 2223,
        density: 9.321,
        groupBlock: "Лантанид",
        yearDiscovered: 1879,
        block: "f",
        cpkHexColor: "00D452",
        period: 6,
        group: 3
    },
    {
        atomicNumber: 70,
        symbol: "Yb",
        name: "Itérbio",
        atomicMass: "173.054",
        electronicConfiguration: "[Xe] 4f14 6s2",
        electronegativity: 1.1,
        atomicRadius: "Неизвестно",
        ionRadius: "102 (+2)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 603,
        electronAffinity: -50,
        oxidationStates: "2, 3",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1092,
        boilingPoint: 1469,
        density: 6.57,
        groupBlock: "Лантанид",
        yearDiscovered: 1878,
        block: "f",
        cpkHexColor: "00BF38",
        period: 6,
        group: 3
    },
    {
        atomicNumber: 71,
        symbol: "Lu",
        name: "Lutécio",
        atomicMass: "174.967",
        electronicConfiguration: "[Xe] 4f14 5d1 6s2",
        electronegativity: 1.27,
        atomicRadius: 160,
        ionRadius: "86.1 (+3)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 524,
        electronAffinity: -50,
        oxidationStates: 3,
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1936,
        boilingPoint: 3675,
        density: 9.841,
        groupBlock: "Лантанид",
        yearDiscovered: 1907,
        block: "d",
        cpkHexColor: "00AB24",
        period: 6,
        group: 3
    },
    {
        atomicNumber: 72,
        symbol: "Hf",
        name: "Háfnio",
        atomicMass: "178.49",
        electronicConfiguration: "[Xe] 4f14 5d2 6s2",
        electronegativity: 1.3,
        atomicRadius: 150,
        ionRadius: "71 (+4)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 659,
        electronAffinity: 0,
        oxidationStates: "2, 3, 4",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 2506,
        boilingPoint: 4876,
        density: 13.31,
        groupBlock: "Полупроводник",
        yearDiscovered: 1923,
        block: "d",
        cpkHexColor: "4DC2FF",
        period: 6,
        group: 4
    },
    {
        atomicNumber: 73,
        symbol: "Ta",
        name: "Tântalo",
        atomicMass: "180.948",
        electronicConfiguration: "[Xe] 4f14 5d3 6s2",
        electronegativity: 1.5,
        atomicRadius: 138,
        ionRadius: "72 (+3)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 761,
        electronAffinity: -31,
        oxidationStates: "-1, 2, 3, 4, 5",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 3290,
        boilingPoint: 5731,
        density: 16.65,
        groupBlock: "Полупроводник",
        yearDiscovered: 1802,
        block: "d",
        cpkHexColor: "4DA6FF",
        period: 6,
        group: 5
    },
    {
        atomicNumber: 74,
        symbol: "W",
        name: "Tungstênio",
        atomicMass: "183.84",
        electronicConfiguration: "[Xe] 4f14 5d4 6s2",
        electronegativity: 2.36,
        atomicRadius: 146,
        ionRadius: "66 (+4)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 770,
        electronAffinity: -79,
        oxidationStates: "-2, -1, 1, 2, 3, 4, 5, 6",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 3695,
        boilingPoint: 5828,
        density: 19.25,
        groupBlock: "Полупроводник",
        yearDiscovered: 1783,
        block: "d",
        cpkHexColor: "2194D6",
        period: 6,
        group: 6
    },
    {
        atomicNumber: 75,
        symbol: "Re",
        name: "Rênio",
        atomicMass: "186.207",
        electronicConfiguration: "[Xe] 4f14 5d5 6s2",
        electronegativity: 1.9,
        atomicRadius: 159,
        ionRadius: "63 (+4)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 760,
        electronAffinity: -15,
        oxidationStates: "-3, -1, 1, 2, 3, 4, 5, 6, 7",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 3459,
        boilingPoint: 5869,
        density: 21.02,
        groupBlock: "Полупроводник",
        yearDiscovered: 1925,
        block: "d",
        cpkHexColor: "267DAB",
        period: 6,
        group: 7
    },
    {
        atomicNumber: 76,
        symbol: "Os",
        name: "Ósmio",
        atomicMass: "190.23",
        electronicConfiguration: "[Xe] 4f14 5d6 6s2",
        electronegativity: 2.2,
        atomicRadius: 128,
        ionRadius: "63 (+4)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 840,
        electronAffinity: -106,
        oxidationStates: "-2, -1, 1, 2, 3, 4, 5, 6, 7, 8",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 3306,
        boilingPoint: 5285,
        density: 22.61,
        groupBlock: "Полупроводник",
        yearDiscovered: 1803,
        block: "d",
        cpkHexColor: "266696",
        period: 6,
        group: 8
    },
    {
        atomicNumber: 77,
        symbol: "Ir",
        name: "Irídio",
        atomicMass: "192.217",
        electronicConfiguration: "[Xe] 4f14 5d7 6s2",
        electronegativity: 2.2,
        atomicRadius: 137,
        ionRadius: "68 (+3)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 880,
        electronAffinity: -151,
        oxidationStates: "-3, -1, 1, 2, 3, 4, 5, 6",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 2739,
        boilingPoint: 4701,
        density: 22.65,
        groupBlock: "Полупроводник",
        yearDiscovered: 1803,
        block: "d",
        cpkHexColor: "175487",
        period: 6,
        group: 9
    },
    {
        atomicNumber: 78,
        symbol: "Pt",
        name: "Platina",
        atomicMass: "195.084",
        electronicConfiguration: "[Xe] 4f14 5d9 6s1",
        electronegativity: 2.28,
        atomicRadius: 128,
        ionRadius: "86 (+2)",
        vanDerWaalsRadius: 175,
        ionizationEnergy: 870,
        electronAffinity: -205,
        oxidationStates: "2, 4, 5, 6",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 2041,
        boilingPoint: 4098,
        density: 21.09,
        groupBlock: "Полупроводник",
        yearDiscovered: "Anciente",
        block: "d",
        cpkHexColor: "D0D0E0",
        period: 6,
        group: 10
    },
    {
        atomicNumber: 79,
        symbol: "Au",
        name: "Ouro",
        atomicMass: "196.967",
        electronicConfiguration: "[Xe] 4f14 5d10 6s1",
        electronegativity: 2.54,
        atomicRadius: 144,
        ionRadius: "137 (+1)",
        vanDerWaalsRadius: 166,
        ionizationEnergy: 890,
        electronAffinity: -223,
        oxidationStates: "-1, 1, 2, 3, 5",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1337,
        boilingPoint: 3129,
        density: 19.3,
        groupBlock: "Полупроводник",
        yearDiscovered: "Anciente",
        block: "d",
        cpkHexColor: "FFD123",
        period: 6,
        group: 11
    },
    {
        atomicNumber: 80,
        symbol: "Hg",
        name: "Mercúrio",
        atomicMass: "200.59",
        electronicConfiguration: "[Xe] 4f14 5d10 6s2",
        electronegativity: 2,
        atomicRadius: 149,
        ionRadius: "119 (+1)",
        vanDerWaalsRadius: 155,
        ionizationEnergy: 1007,
        electronAffinity: 0,
        oxidationStates: "1, 2, 4",
        standardState: "Жидкий",
        bondingType: "Metálica",
        meltingPoint: 234,
        boilingPoint: 630,
        density: 13.534,
        groupBlock: "Полупроводник",
        yearDiscovered: "Anciente",
        block: "d",
        cpkHexColor: "B8B8D0",
        period: 6,
        group: 12
    },
    {
        atomicNumber: 81,
        symbol: "Tl",
        name: "Tálio",
        atomicMass: "204.383",
        electronicConfiguration: "[Xe] 4f14 5d10 6s2 6p1",
        electronegativity: 2.04,
        atomicRadius: 148,
        ionRadius: "150 (+1)",
        vanDerWaalsRadius: 196,
        ionizationEnergy: 589,
        electronAffinity: -19,
        oxidationStates: "1, 3",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 577,
        boilingPoint: 1746,
        density: 11.85,
        groupBlock: "Металл",
        yearDiscovered: 1861,
        block: "p",
        cpkHexColor: "A6544D",
        period: 6,
        group: 13
    },
    {
        atomicNumber: 82,
        symbol: "Pb",
        name: "Chumbo",
        atomicMass: "207.20",
        electronicConfiguration: "[Xe] 4f14 5d10 6s2 6p2",
        electronegativity: 2.33,
        atomicRadius: 147,
        ionRadius: "119 (+2)",
        vanDerWaalsRadius: 202,
        ionizationEnergy: 716,
        electronAffinity: -35,
        oxidationStates: "-4, 2, 4",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 601,
        boilingPoint: 2022,
        density: 11.34,
        groupBlock: "Металл",
        yearDiscovered: "Anciente",
        block: "p",
        cpkHexColor: "575961",
        period: 6,
        group: 14
    },
    {
        atomicNumber: 83,
        symbol: "Bi",
        name: "Bismuto",
        atomicMass: "208.980",
        electronicConfiguration: "[Xe] 4f14 5d10 6s2 6p3",
        electronegativity: 2.02,
        atomicRadius: 146,
        ionRadius: "103 (+3)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 703,
        electronAffinity: -91,
        oxidationStates: "-3, 3, 5",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 544,
        boilingPoint: 1837,
        density: 9.78,
        groupBlock: "Металл",
        yearDiscovered: "Anciente",
        block: "p",
        cpkHexColor: "9E4FB5",
        period: 6,
        group: 15
    },
    {
        atomicNumber: 84,
        symbol: "Po",
        name: "Polônio",
        atomicMass: "209",
        electronicConfiguration: "[Xe] 4f14 5d10 6s2 6p4",
        electronegativity: 2,
        atomicRadius: "Неизвестно",
        ionRadius: "94 (+4)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 812,
        electronAffinity: -183,
        oxidationStates: "-2, 2, 4, 6",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 527,
        boilingPoint: 1235,
        density: 9.196,
        groupBlock: "Полуметалл",
        yearDiscovered: 1898,
        block: "p",
        cpkHexColor: "AB5C00",
        period: 6,
        group: 16
    },
    {
        atomicNumber: 85,
        symbol: "At",
        name: "Ástato",
        atomicMass: "210",
        electronicConfiguration: "[Xe] 4f14 5d10 6s2 6p5",
        electronegativity: 2.2,
        atomicRadius: "Неизвестно",
        ionRadius: "62 (+7)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 920,
        electronAffinity: -270,
        oxidationStates: "-1, 1, 3, 5",
        standardState: "Твердый",
        bondingType: "covalent network",
        meltingPoint: 575,
        boilingPoint: "Неизвестно",
        density: "Неизвестно",
        groupBlock: "Галлоген",
        yearDiscovered: 1940,
        block: "p",
        cpkHexColor: "754F45",
        period: 6,
        group: 17
    },
    {
        atomicNumber: 86,
        symbol: "Rn",
        name: "Rádon",
        atomicMass: "222",
        electronicConfiguration: "[Xe] 4f14 5d10 6s2 6p6",
        electronegativity: "Неизвестно",
        atomicRadius: 145,
        ionRadius: "Неизвестно",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 1037,
        electronAffinity: "Неизвестно",
        oxidationStates: 2,
        standardState: "Газообразный",
        bondingType: "atomic",
        meltingPoint: 202,
        boilingPoint: 211,
        density: 0.00973,
        groupBlock: "Инертный газ",
        yearDiscovered: 1900,
        block: "p",
        cpkHexColor: "428296",
        period: 6,
        group: 18
    },
    {
        atomicNumber: 87,
        symbol: "Fr",
        name: "Frâncio",
        atomicMass: "223",
        electronicConfiguration: "[Rn] 7s1",
        electronegativity: 0.7,
        atomicRadius: "Неизвестно",
        ionRadius: "180 (+1)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 380,
        electronAffinity: "Неизвестно",
        oxidationStates: 1,
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: "Неизвестно",
        boilingPoint: "Неизвестно",
        density: "Неизвестно",
        groupBlock: "Щелочной металл",
        yearDiscovered: 1939,
        block: "s",
        cpkHexColor: "420066",
        period: 7,
        group: 1
    },
    {
        atomicNumber: 88,
        symbol: "Ra",
        name: "Rádio",
        atomicMass:"226",
        electronicConfiguration: "[Rn] 7s2",
        electronegativity: 0.9,
        atomicRadius: "Неизвестно",
        ionRadius: "148 (+2)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 509,
        electronAffinity: "Неизвестно",
        oxidationStates: 2,
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 973,
        boilingPoint: 2010,
        density: 5,
        groupBlock: "Щелочноземельный металл",
        yearDiscovered: 1898,
        block: "s",
        cpkHexColor: "007D00",
        period: 7,
        group: 2
    },
    {
        atomicNumber: 89,
        symbol: "Ac",
        name: "Actínio",
        atomicMass: "227",
        electronicConfiguration: "[Rn] 6d1 7s2",
        electronegativity: 1.1,
        atomicRadius: "Неизвестно",
        ionRadius: "112 (+3)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 499,
        electronAffinity: "Неизвестно",
        oxidationStates: 3,
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1323,
        boilingPoint: 3473,
        density: 10.07,
        groupBlock: "Актинид",
        yearDiscovered: 1899,
        block: "f",
        cpkHexColor: "#70ABFA",
        period: 7,
        group: 3
    },
    {
        atomicNumber: 90,
        symbol: "Th",
        name: "Tório",
        atomicMass: "232.038",
        electronicConfiguration: "[Rn] 6d2 7s2",
        electronegativity: 1.3,
        atomicRadius: "Неизвестно",
        ionRadius: "94 (+4)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 587,
        electronAffinity: "Неизвестно",
        oxidationStates: "2, 3, 4",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 2023,
        boilingPoint: 5093,
        density: 11.724,
        groupBlock: "Актинид",
        yearDiscovered: 1828,
        block: "f",
        cpkHexColor: "00BAFF",
        period: 7,
        group: 3
    },
    {
        atomicNumber: 91,
        symbol: "Pa",
        name: "Protactínio",
        atomicMass: "231.036",
        electronicConfiguration: "[Rn] 5f2 6d1 7s2",
        electronegativity: 1.5,
        atomicRadius: "Неизвестно",
        ionRadius: "104 (+3)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 568,
        electronAffinity: "Неизвестно",
        oxidationStates: "3, 4, 5",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1845,
        boilingPoint: 4273,
        density: 15.37,
        groupBlock: "Актинид",
        yearDiscovered: 1913,
        block: "f",
        cpkHexColor: "00A1FF",
        period: 7,
        group: 3
    },
    {
        atomicNumber: 92,
        symbol: "U",
        name: "Urânio",
        atomicMass: "238.029",
        electronicConfiguration: "[Rn] 5f3 6d1 7s2",
        electronegativity: 1.38,
        atomicRadius: "Неизвестно",
        ionRadius: "102.5 (+3)",
        vanDerWaalsRadius: 186,
        ionizationEnergy: 598,
        electronAffinity: "Неизвестно",
        oxidationStates: "3, 4, 5, 6",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1408,
        boilingPoint: 4200,
        density: 19.05,
        groupBlock: "Актинид",
        yearDiscovered: 1789,
        block: "f",
        cpkHexColor: "008FFF",
        period: 7,
        group: 3
    },
    {
        atomicNumber: 93,
        symbol: "Np",
        name: "Neptúnio",
        atomicMass: "237",
        electronicConfiguration: "[Rn] 5f4 6d1 7s2",
        electronegativity: 1.36,
        atomicRadius: "Неизвестно",
        ionRadius: "110 (+2)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 605,
        electronAffinity: "Неизвестно",
        oxidationStates: "3, 4, 5, 6, 7",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 917,
        boilingPoint: 4273,
        density: 20.45,
        groupBlock: "Актинид",
        yearDiscovered: 1940,
        block: "f",
        cpkHexColor: "0080FF",
        period: 7,
        group: 3
    },
    {
        atomicNumber: 94,
        symbol: "Pu",
        name: "Plutónio",
        atomicMass: "244",
        electronicConfiguration: "[Rn] 5f6 7s2",
        electronegativity: 1.28,
        atomicRadius: "Неизвестно",
        ionRadius: "100 (+3)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 585,
        electronAffinity: "Неизвестно",
        oxidationStates: "3, 4, 5, 6, 7",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 913,
        boilingPoint: 3503,
        density: 19.816,
        groupBlock: "Актинид",
        yearDiscovered: 1940,
        block: "f",
        cpkHexColor: "006BFF",
        period: 7,
        group: 3
    },
    {
        atomicNumber: 95,
        symbol: "Am",
        name: "Amerício",
        atomicMass: "243",
        electronicConfiguration: "[Rn] 5f7 7s2",
        electronegativity: 1.3,
        atomicRadius: "Неизвестно",
        ionRadius: "126 (+2)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 578,
        electronAffinity: "Неизвестно",
        oxidationStates: "2, 3, 4, 5, 6",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1449,
        boilingPoint: 2284,
        density: "Неизвестно",
        groupBlock: "Актинид",
        yearDiscovered: 1944,
        block: "f",
        cpkHexColor: "545CF2",
        period: 7,
        group: 3
    },
    {
        atomicNumber: 96,
        symbol: "Cm",
        name: "Cúrio",
        atomicMass: "247",
        electronicConfiguration: "[Rn] 5f7 6d1 7s2",
        electronegativity: 1.3,
        atomicRadius: "Неизвестно",
        ionRadius: "97 (+3)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 581,
        electronAffinity: "Неизвестно",
        oxidationStates: "3, 4",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1618,
        boilingPoint: 3383,
        density: 13.51,
        groupBlock: "Актинид",
        yearDiscovered: 1944,
        block: "f",
        cpkHexColor: "785CE3",
        period: 7,
        group: 3
    },
    {
        atomicNumber: 97,
        symbol: "Bk",
        name: "Berquélio",
        atomicMass: "247",
        electronicConfiguration: "[Rn] 5f9 7s2",
        electronegativity: 1.3,
        atomicRadius: "Неизвестно",
        ionRadius: "96 (+3)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 601,
        electronAffinity: "Неизвестно",
        oxidationStates: "3, 4",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1323,
        boilingPoint: "Неизвестно",
        density: 14.78,
        groupBlock: "Актинид",
        yearDiscovered: 1949,
        block: "f",
        cpkHexColor: "8A4FE3",
        period: 7,
        group: 3
    },
    {
        atomicNumber: 98,
        symbol: "Cf",
        name: "Califórnio",
        atomicMass:"251",
        electronicConfiguration: "[Rn] 5f10 7s2",
        electronegativity: 1.3,
        atomicRadius: "Неизвестно",
        ionRadius: "95 (+3)",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 608,
        electronAffinity: "Неизвестно",
        oxidationStates: "2, 3, 4",
        standardState: "Твердый",
        bondingType: "Metálica",
        meltingPoint: 1173,
        boilingPoint: "Неизвестно",
        density: 15.1,
        groupBlock: "Актинид",
        yearDiscovered: 1950,
        block: "f",
        cpkHexColor: "A136D4",
        period: 7,
        group: 3
    },
    {
        atomicNumber: 99,
        symbol: "Es",
        name: "Einstênio",
        atomicMass: "252",
        electronicConfiguration: "[Rn] 5f11 7s2",
        electronegativity: 1.3,
        atomicRadius: "Неизвестно",
        ionRadius: "Неизвестно",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 619,
        electronAffinity: "Неизвестно",
        oxidationStates: "2, 3",
        standardState: "Твердый",
        bondingType: "Неизвестно",
        meltingPoint: 1133,
        boilingPoint: "Неизвестно",
        density: "Неизвестно",
        groupBlock: "Актинид",
        yearDiscovered: 1952,
        block: "f",
        cpkHexColor: "B31FD4",
        period: 7,
        group: 3
    },
    {
        atomicNumber: 100,
        symbol: "Fm",
        name: "Férmio",
        atomicMass:"257",
        electronicConfiguration: "[Rn] 5f12 7s2",
        electronegativity: 1.3,
        atomicRadius: "Неизвестно",
        ionRadius: "Неизвестно",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 627,
        electronAffinity: "Неизвестно",
        oxidationStates: "2, 3",
        standardState: "Неизвестно",
        bondingType: "Неизвестно",
        meltingPoint: 1800,
        boilingPoint: "Неизвестно",
        density: "Неизвестно",
        groupBlock: "Актинид",
        yearDiscovered: 1952,
        block: "f",
        cpkHexColor: "B31FBA",
        period: 7,
        group: 3
    },
    {
        atomicNumber: 101,
        symbol: "Md",
        name: "Mendelévio",
        atomicMass:"258",
        electronicConfiguration: "[Rn] 5f13 7s2",
        electronegativity: 1.3,
        atomicRadius: "Неизвестно",
        ionRadius: "Неизвестно",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 635,
        electronAffinity: "Неизвестно",
        oxidationStates: "2, 3",
        standardState: "Неизвестно",
        bondingType: "Неизвестно",
        meltingPoint: 1100,
        boilingPoint: "Неизвестно",
        density: "Неизвестно",
        groupBlock: "Актинид",
        yearDiscovered: 1955,
        block: "f",
        cpkHexColor: "B30DA6",
        period: 7,
        group: 3
    },
    {
        atomicNumber: 102,
        symbol: "No",
        name: "Nobélio",
        atomicMass:"259",
        electronicConfiguration: "[Rn] 5f14 7s2",
        electronegativity: 1.3,
        atomicRadius: "Неизвестно",
        ionRadius: "Неизвестно",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: 642,
        electronAffinity: "Неизвестно",
        oxidationStates: "2, 3",
        standardState: "Неизвестно",
        bondingType: "Неизвестно",
        meltingPoint: 1100,
        boilingPoint: "Неизвестно",
        density: "Неизвестно",
        groupBlock: "Актинид",
        yearDiscovered: 1957,
        block: "f",
        cpkHexColor: "BD0D87",
        period: 7,
        group: 3
    },
    {
        atomicNumber: 103,
        symbol: "Lr",
        name: "Laurêncio",
        atomicMass: "262",
        electronicConfiguration: "[Rn] 5f14 7s2 7p1",
        electronegativity: 1.3,
        atomicRadius: "Неизвестно",
        ionRadius: "Неизвестно",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: "Неизвестно",
        electronAffinity: "Неизвестно",
        oxidationStates: 3,
        standardState: "Неизвестно",
        bondingType: "Неизвестно",
        meltingPoint: 1900,
        boilingPoint: "Неизвестно",
        density: "Неизвестно",
        groupBlock: "Актинид",
        yearDiscovered: 1961,
        block: "d",
        cpkHexColor: "C70066",
        period: 7,
        group: 3
    },
    {
        atomicNumber: 104,
        symbol: "Rf",
        name: "Rutherfórdio",
        atomicMass: "267",
        electronicConfiguration: "[Rn] 5f14 6d2 7s2",
        electronegativity: "Неизвестно",
        atomicRadius: "Неизвестно",
        ionRadius: "Неизвестно",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: "Неизвестно",
        electronAffinity: "Неизвестно",
        oxidationStates: 4,
        standardState: "Неизвестно",
        bondingType: "Неизвестно",
        meltingPoint: "Неизвестно",
        boilingPoint: "Неизвестно",
        density: "Неизвестно",
        groupBlock: "Полупроводник",
        yearDiscovered: 1969,
        block: "d",
        cpkHexColor: "CC0059",
        period: 7,
        group: 4
    },
    {
        atomicNumber: 105,
        symbol: "Db",
        name: "Dúbnio",
        atomicMass: "268",
        electronicConfiguration: "[Rn] 5f14 6d3 7s2",
        electronegativity: "Неизвестно",
        atomicRadius: "Неизвестно",
        ionRadius: "Неизвестно",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: "Неизвестно",
        electronAffinity: "Неизвестно",
        oxidationStates: "Неизвестно",
        standardState: "Неизвестно",
        bondingType: "Неизвестно",
        meltingPoint: "Неизвестно",
        boilingPoint: "Неизвестно",
        density: "Неизвестно",
        groupBlock: "Полупроводник",
        yearDiscovered: 1967,
        block: "d",
        cpkHexColor: "D1004F",
        period: 7,
        group: 5
    },
    {
        atomicNumber: 106,
        symbol: "Sg",
        name: "Seabórgio",
        atomicMass:"269",
        electronicConfiguration: "[Rn] 5f14 6d4 7s2",
        electronegativity: "Неизвестно",
        atomicRadius: "Неизвестно",
        ionRadius: "Неизвестно",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: "Неизвестно",
        electronAffinity: "Неизвестно",
        oxidationStates: "Неизвестно",
        standardState: "Неизвестно",
        bondingType: "Неизвестно",
        meltingPoint: "Неизвестно",
        boilingPoint: "Неизвестно",
        density: "Неизвестно",
        groupBlock: "Полупроводник",
        yearDiscovered: 1974,
        block: "d",
        cpkHexColor: "D90045",
        period: 7,
        group: 6
    },
    {
        atomicNumber: 107,
        symbol: "Bh",
        name: "Bóhrio",
        atomicMass: "270",
        electronicConfiguration: "[Rn] 5f14 6d5 7s2",
        electronegativity: "Неизвестно",
        atomicRadius: "Неизвестно",
        ionRadius: "Неизвестно",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: "Неизвестно",
        electronAffinity: "Неизвестно",
        oxidationStates: "Неизвестно",
        standardState: "Неизвестно",
        bondingType: "Неизвестно",
        meltingPoint: "Неизвестно",
        boilingPoint: "Неизвестно",
        density: "Неизвестно",
        groupBlock: "Полупроводник",
        yearDiscovered: 1976,
        block: "d",
        cpkHexColor: "E00038",
        period: 7,
        group: 7
    },
    {
        atomicNumber: 108,
        symbol: "Hs",
        name: "Hássio",
        atomicMass: "277",
        electronicConfiguration: "[Rn] 5f14 6d6 7s2",
        electronegativity: "Неизвестно",
        atomicRadius: "Неизвестно",
        ionRadius: "Неизвестно",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: "Неизвестно",
        electronAffinity: "Неизвестно",
        oxidationStates: "Неизвестно",
        standardState: "Неизвестно",
        bondingType: "Неизвестно",
        meltingPoint: "Неизвестно",
        boilingPoint: "Неизвестно",
        density: "Неизвестно",
        groupBlock: "Полупроводник",
        yearDiscovered: 1984,
        block: "d",
        cpkHexColor: "E6002E",
        period: 7,
        group: 8
    },
    {
        atomicNumber: 109,
        symbol: "Mt",
        name: "Meitnério",
        atomicMass: "278",
        electronicConfiguration: "[Rn] 5f14 6d7 7s2",
        electronegativity: "Неизвестно",
        atomicRadius: "Неизвестно",
        ionRadius: "Неизвестно",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: "Неизвестно",
        electronAffinity: "Неизвестно",
        oxidationStates: "Неизвестно",
        standardState: "Неизвестно",
        bondingType: "Неизвестно",
        meltingPoint: "Неизвестно",
        boilingPoint: "Неизвестно",
        density: "Неизвестно",
        groupBlock: "Полупроводник",
        yearDiscovered: 1982,
        block: "d",
        cpkHexColor: "EB0026",
        period: 7,
        group: 9
    },
    {
        atomicNumber: 110,
        symbol: "Ds",
        name: "Darmstádtio",
        atomicMass: "281",
        electronicConfiguration: "[Rn] 5f14 6d9 7s1",
        electronegativity: "Неизвестно",
        atomicRadius: "Неизвестно",
        ionRadius: "Неизвестно",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: "Неизвестно",
        electronAffinity: "Неизвестно",
        oxidationStates: "Неизвестно",
        standardState: "Неизвестно",
        bondingType: "Неизвестно",
        meltingPoint: "Неизвестно",
        boilingPoint: "Неизвестно",
        density: "Неизвестно",
        groupBlock: "Полупроводник",
        yearDiscovered: 1994,
        block: "d",
        cpkHexColor: "Неизвестно",
        period: 7,
        group: 10
    },
    {
        atomicNumber: 111,
        symbol: "Rg",
        name: "Roentgênio",
        atomicMass: "280",
        electronicConfiguration: "[Rn] 5f14 6d10 7s1",
        electronegativity: "Неизвестно",
        atomicRadius: "Неизвестно",
        ionRadius: "Неизвестно",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: "Неизвестно",
        electronAffinity: "Неизвестно",
        oxidationStates: "Неизвестно",
        standardState: "Неизвестно",
        bondingType: "Неизвестно",
        meltingPoint: "Неизвестно",
        boilingPoint: "Неизвестно",
        density: "Неизвестно",
        groupBlock: "Полупроводник",
        yearDiscovered: 1994,
        block: "d",
        cpkHexColor: "Неизвестно",
        period: 7,
        group: 11
    },
    {
        atomicNumber: 112,
        symbol: "Cn",
        name: "Copernício",
        atomicMass: "285",
        electronicConfiguration: "[Rn] 5f14 6d10 7s2",
        electronegativity: "Неизвестно",
        atomicRadius: "Неизвестно",
        ionRadius: "Неизвестно",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: "Неизвестно",
        electronAffinity: "Неизвестно",
        oxidationStates: "Неизвестно",
        standardState: "Неизвестно",
        bondingType: "Неизвестно",
        meltingPoint: "Неизвестно",
        boilingPoint: "Неизвестно",
        density: "Неизвестно",
        groupBlock: "Полупроводник",
        yearDiscovered: 1996,
        block: "d",
        cpkHexColor: "Неизвестно",
        period: 7,
        group: 12
    },
    {
        atomicNumber: 113,
        symbol: "Nh",
        name: "Nihonium",
        atomicMass: "284",
        electronicConfiguration: "[Rn] 5f14 6d10 7s2 7p1",
        electronegativity: "Неизвестно",
        atomicRadius: "Неизвестно",
        ionRadius: "Неизвестно",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: "Неизвестно",
        electronAffinity: "Неизвестно",
        oxidationStates: "Неизвестно",
        standardState: "Неизвестно",
        bondingType: "Неизвестно",
        meltingPoint: "Неизвестно",
        boilingPoint: "Неизвестно",
        density: "Неизвестно",
        groupBlock: "Металл",
        yearDiscovered: 2003,
        block: "p",
        cpkHexColor: "Неизвестно",
        period: 7,
        group: 13
    },
    {
        atomicNumber: 114,
        symbol: "Fl",
        name: "Fleróvio",
        atomicMass: "289",
        electronicConfiguration: "[Rn] 5f14 6d10 7s2 7p2",
        electronegativity: "Неизвестно",
        atomicRadius: "Неизвестно",
        ionRadius: "Неизвестно",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: "Неизвестно",
        electronAffinity: "Неизвестно",
        oxidationStates: "Неизвестно",
        standardState: "Неизвестно",
        bondingType: "Неизвестно",
        meltingPoint: "Неизвестно",
        boilingPoint: "Неизвестно",
        density: "Неизвестно",
        groupBlock: "Металл",
        yearDiscovered: 1998,
        block: "p",
        cpkHexColor: "Неизвестно",
        period: 7,
        group: 14
    },
    {
        atomicNumber: 115,
        symbol: "Mc",
        name: "Moscóvio",
        atomicMass: "288",
        electronicConfiguration: "[Rn] 5f14 6d10 7s2 7p3",
        electronegativity: "Неизвестно",
        atomicRadius: "Неизвестно",
        ionRadius: "Неизвестно",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: "Неизвестно",
        electronAffinity: "Неизвестно",
        oxidationStates: "Неизвестно",
        standardState: "Неизвестно",
        bondingType: "Неизвестно",
        meltingPoint: "Неизвестно",
        boilingPoint: "Неизвестно",
        density: "Неизвестно",
        groupBlock: "Металл",
        yearDiscovered: 2003,
        block: "p",
        cpkHexColor: "Неизвестно",
        period: 7,
        group: 15
    },
    {
        atomicNumber: 116,
        symbol: "Lv",
        name: "Livermório",
        atomicMass: "293",
        electronicConfiguration: "[Rn] 5f14 6d10 7s2 7p4",
        electronegativity: "Неизвестно",
        atomicRadius: "Неизвестно",
        ionRadius: "Неизвестно",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: "Неизвестно",
        electronAffinity: "Неизвестно",
        oxidationStates: "Неизвестно",
        standardState: "Неизвестно",
        bondingType: "Неизвестно",
        meltingPoint: "Неизвестно",
        boilingPoint: "Неизвестно",
        density: "Неизвестно",
        groupBlock: "Металл",
        yearDiscovered: 2000,
        block: "p",
        cpkHexColor: "Неизвестно",
        period: 7,
        group: 16
    },
    {
        atomicNumber: 117,
        symbol: "Ts",
        name: "Tenesso",
        atomicMass: "294",
        electronicConfiguration: "[Rn] 5f14 6d10 7s2 7p5",
        electronegativity: "Неизвестно",
        atomicRadius: "Неизвестно",
        ionRadius: "Неизвестно",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: "Неизвестно",
        electronAffinity: "Неизвестно",
        oxidationStates: "Неизвестно",
        standardState: "Неизвестно",
        bondingType: "Неизвестно",
        meltingPoint: "Неизвестно",
        boilingPoint: "Неизвестно",
        density: "Неизвестно",
        groupBlock: "Металл",
        yearDiscovered: 2010,
        block: "p",
        cpkHexColor: "Неизвестно",
        period: 7,
        group: 17
    },
    {
        atomicNumber: 118,
        symbol: "Og",
        name: "Oganesson",
        atomicMass: "294",
        electronicConfiguration: `[Rn] 5f14 6d10 7s2 7p6`,
        electronegativity: "Неизвестно",
        atomicRadius: "Неизвестно",
        ionRadius: "Неизвестно",
        vanDerWaalsRadius: "Неизвестно",
        ionizationEnergy: "Неизвестно",
        electronAffinity: "Неизвестно",
        oxidationStates: "Неизвестно",
        standardState: "Неизвестно",
        bondingType: "Неизвестно",
        meltingPoint: "Неизвестно",
        boilingPoint: "Неизвестно",
        density: "Неизвестно",
        groupBlock: "Инертный газ",
        yearDiscovered: 2002,
        block: "p",
        cpkHexColor: "Неизвестно",
        period: 7,
        group: 18
    }
]

export default Elementos;
